version: 2

project_name: mapps

before:
  hooks:
    - go mod tidy

builds:
  - id: mapps
    main: ./cmd/mapps
    binary: mapps
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Tag}}

archives:
  - id: mapps
    formats: [binary]
    name_template: "mapps_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
