package wrappers

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func bodyAfterFrontmatter(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile %s: %v", path, err)
	}
	i := strings.Index(string(data), "<!-- Generated by mapps")
	if i < 0 {
		t.Fatalf("%s has no '<!-- Generated by mapps' marker", path)
	}
	return string(data)[i:]
}

func TestWrite_CreatesAllThreeFiles(t *testing.T) {
	root := t.TempDir()
	if err := Write(root); err != nil {
		t.Fatalf("Write: %v", err)
	}

	for _, dest := range []string{
		filepath.Join(root, ".claude", "skills", "mapps", "SKILL.md"),
		filepath.Join(root, ".opencode", "commands", "mapps.md"),
		filepath.Join(root, "PROMPT-map.md"),
	} {
		if _, err := os.Stat(dest); err != nil {
			t.Errorf("expected %s to exist: %v", dest, err)
		}
	}
}

func TestWrite_Idempotent(t *testing.T) {
	root := t.TempDir()
	if err := Write(root); err != nil {
		t.Fatalf("Write (1st): %v", err)
	}
	if err := Write(root); err != nil {
		t.Fatalf("Write (2nd): %v", err)
	}
}

func TestWrite_SkillAndCommandBodiesMatch(t *testing.T) {
	root := t.TempDir()
	if err := Write(root); err != nil {
		t.Fatalf("Write: %v", err)
	}

	skillBody := bodyAfterFrontmatter(t, filepath.Join(root, ".claude", "skills", "mapps", "SKILL.md"))
	commandBody := bodyAfterFrontmatter(t, filepath.Join(root, ".opencode", "commands", "mapps.md"))

	if skillBody != commandBody {
		t.Errorf("skill body and command body differ after frontmatter:\nskill:\n%s\ncommand:\n%s", skillBody, commandBody)
	}
}

func TestWrite_MentionsInstallCommand(t *testing.T) {
	root := t.TempDir()
	if err := Write(root); err != nil {
		t.Fatalf("Write: %v", err)
	}

	want := "go install github.com/rus-lan/multiApps/cmd/mapps@latest"
	for _, dest := range []string{
		filepath.Join(root, ".claude", "skills", "mapps", "SKILL.md"),
		filepath.Join(root, ".opencode", "commands", "mapps.md"),
		filepath.Join(root, "PROMPT-map.md"),
	} {
		data, err := os.ReadFile(dest)
		if err != nil {
			t.Fatalf("ReadFile %s: %v", dest, err)
		}
		if !strings.Contains(string(data), want) {
			t.Errorf("%s does not mention %q", dest, want)
		}
	}
}

func TestWrite_MentionsResultsDir(t *testing.T) {
	root := t.TempDir()
	if err := Write(root); err != nil {
		t.Fatalf("Write: %v", err)
	}

	for _, dest := range []string{
		filepath.Join(root, ".claude", "skills", "mapps", "SKILL.md"),
		filepath.Join(root, ".opencode", "commands", "mapps.md"),
		filepath.Join(root, "PROMPT-map.md"),
	} {
		data, err := os.ReadFile(dest)
		if err != nil {
			t.Fatalf("ReadFile %s: %v", dest, err)
		}
		if !strings.Contains(string(data), "results/") {
			t.Errorf("%s does not mention results/", dest)
		}
	}
}
